/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.applet.AudioClip;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian
 */
public class IngresoUsuario extends javax.swing.JFrame implements Serializable {

    public IngresoUsuario() {
        initComponents();
        ImageIcon d = new ImageIcon("C:\\Users\\edgar\\OneDrive\\Documentos\\NetBeansProjects\\Juego-Algoritmos\\src\\imagenes\\ayuda\\AnyConv.com__Tus personajes favoritos de la infancia se han convertido en psicópatas _ Ilustración.png");
        Icon id = new ImageIcon(d.getImage().getScaledInstance(lb3.getWidth(), lb3.getHeight(), Image.SCALE_DEFAULT));
        lb3.setIcon(id);
        ImageIcon de = new ImageIcon("C:\\Users\\edgar\\OneDrive\\Documentos\\NetBeansProjects\\Juego-Algoritmos\\src\\imagenes\\ayuda\\inicio secion.gif");
        Icon ide = new ImageIcon(de.getImage().getScaledInstance(imag.getWidth(), imag.getHeight(), Image.SCALE_DEFAULT));
        imag.setIcon(ide);
        setLocationRelativeTo(null);
        jPanel1.setOpaque(true);
        jPanel1.setBackground(new Color(255, 255, 0, 100));
        this.setLocationRelativeTo(this);

    }

    /**
     * Creates new form IngresoUsuario
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        imag = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        pass3 = new javax.swing.JPasswordField();
        Ingresar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnIngresar1 = new javax.swing.JButton();
        lb3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jLabel2.setText("Contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 70, 31));
        jPanel1.add(imag, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 500, 440));
        jPanel1.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 170, 30));
        jPanel1.add(pass3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 170, 30));

        Ingresar.setBackground(new java.awt.Color(204, 204, 204));
        Ingresar.setForeground(new java.awt.Color(51, 51, 51));
        Ingresar.setText("Ingresar");
        Ingresar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true)));
        Ingresar.setMargin(new java.awt.Insets(2, 14, 0, 14));
        Ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IngresarMouseExited(evt);
            }
        });
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        jPanel1.add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 270, 43));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jLabel6.setText("Nombre:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 80, 27));

        btnIngresar1.setBackground(new java.awt.Color(204, 204, 204));
        btnIngresar1.setForeground(new java.awt.Color(51, 51, 51));
        btnIngresar1.setText("Registrarse");
        btnIngresar1.setAutoscrolls(true);
        btnIngresar1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N
        btnIngresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresar1MouseExited(evt);
            }
        });
        btnIngresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 270, 43));

        lb3.setForeground(java.awt.Color.darkGray);
        lb3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 160, 160));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel3.setText("Inicio Sesion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 110, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean buscarUsuario(String nombre, String contraseña) throws FileNotFoundException, IOException {
        boolean bandera = false;
        Registro p = new Registro();
        if (p.archivoVacio("ingreso.txt")) {
            FileReader fr = new FileReader(p.archivoIn);
            BufferedReader br = new BufferedReader(fr);
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] cod = linea.split("-");
                if (cod[0].equals(nombre) && cod[1].equals(contraseña)) {
                    bandera = true;
                } else {
                    bandera = false;
                }
            }
            br.close();
            fr.close();
        }
        return bandera;
    }
    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        try {
            // TODO add your handling code here:

            if (buscarUsuario(txt1.getText(), pass3.getText()) == true) {
                JOptionPane.showMessageDialog(null, "Bienvenido " + txt1.getText());
                VistaMenu v = new VistaMenu(this, true);
                v.setVisible(true);
                this.dispose();

            } else {
                if (txt1.getText().equals("") && pass3.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Campos Vacios Ingrese Usuario y Contraseña");
                } else {
                    JOptionPane.showMessageDialog(null, "Usuario o Contraseña mal ingresados");
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(IngresoUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_IngresarActionPerformed

    private void btnIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar1ActionPerformed
        Registro d = new Registro();
        d.setVisible(true);


    }//GEN-LAST:event_btnIngresar1ActionPerformed

    private void btnIngresar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresar1MouseEntered
        btnIngresar1.setBackground(Color.ORANGE);

    }//GEN-LAST:event_btnIngresar1MouseEntered

    private void btnIngresar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresar1MouseExited
        btnIngresar1.setBackground(new Color(102, 102, 102));

    }//GEN-LAST:event_btnIngresar1MouseExited

    private void IngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarMouseEntered
        Ingresar.setBackground(Color.ORANGE);
    }//GEN-LAST:event_IngresarMouseEntered

    private void IngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarMouseExited
        Ingresar.setBackground(new Color(102, 120, 120));
    }//GEN-LAST:event_IngresarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ingresar;
    private javax.swing.JButton btnIngresar1;
    private javax.swing.JLabel imag;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb3;
    private javax.swing.JPasswordField pass3;
    private javax.swing.JTextField txt1;
    // End of variables declaration//GEN-END:variables
}
